envs:
  NODE_VERSION: 14.16.0

tasks:
  build:
    description: build source code
    deps: [ npm:install, hsr-browser:build ]
    generates:
      - ../../dist/hsr-node
    mounts:
      - node_modules
    src:
      - src
      - package.json
      - tsconfig.json
    cmds:
      - node_modules/.bin/tsc -b
      - cp package.json ../../dist/hsr-node

references:
  hsr-browser: ../hsr-browser/build.yaml

includes:
  npm: ../../build.npm.yaml
