tasks:
  test:
    description: test packages
    deps: [hsr-tests:test]

  publish:
    description: publish npm package
    deps:
      - hsr-browser:npm:publish
      - hsr-node:npm:publish
      - hsr-node-rpc:npm:publish
      - hsr-browser-rpc:npm:publish
      - hsr-node-static:npm:publish
      - hsr-node-typescript:npm:publish

  build:
    description: build hsr
    deps:
      - hsr-browser:build
      - hsr-browser-rpc:build
      - hsr-node:build
      - hsr-node-rpc:build
      - hsr-node-static:build
      - hsr-node-typescript:build
      - hsr-tests:build

references:
  hsr-node: ./packages/hsr-node/build.yaml
  hsr-node-rpc: ./packages/hsr-node-rpc/build.yaml
  hsr-node-static: ./packages/hsr-node-static/build.yaml
  hsr-node-typescript: ./packages/hsr-node-typescript/build.yaml
  hsr-browser: ./packages/hsr-browser/build.yaml
  hsr-browser-rpc: ./packages/hsr-browser-rpc/build.yaml
  hsr-tests: ./tests/hsr-tests/build.yaml
