rm -rf dist || true
rm -rf coverage || true
rm -rf node_modules || true
rm -rf packages/hsr-browser/node_modules || true
rm -rf packages/hsr-browser-rpc/node_modules || true
rm -rf packages/hsr-node/node_modules || true
rm -rf packages/hsr-node-static/node_modules || true
rm -rf packages/hsr-node-rpc/node_modules || true
rm -rf packages/hsr-node-typescript/node_modules || true
