envs:
  NODE_VERSION: 14.16.0

tasks:
  build:
    description: build source code
    deps: [ npm:install, hsr-node:build, hsr-browser:build, hsr-browser-rpc:build ]
    generates:
      - ../../dist/hsr-node-rpc
    src:
      - src
      - tsconfig.json
      - package.json
    cmds:
      - node_modules/.bin/tsc -b
      - cp package.json ../../dist/hsr-node-rpc

references:
  hsr-browser-rpc: ../hsr-browser-rpc/build.yaml
  hsr-node: ../hsr-node/build.yaml
  hsr-browser: ../hsr-browser/build.yaml

includes:
  npm: ../../build.npm.yaml
