tasks:
  build:
    deps: [hsr-node:build, hsr-browser-rpc:build]
    extend: npm:build

references:
  hsr-browser-rpc: ../hsr-browser-rpc/build.yaml
  hsr-node: ../hsr-node/build.yaml

includes:
  npm: ../../build.npm.yaml
