name: build & test
on:
  push:
    branches:

jobs:
  build:
    name: Build hsr
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm ci
        working-directory: packages/hsr-browser
      - run: npm ci
        working-directory: packages/hsr-browser-rpc
      - run: npm ci
        working-directory: packages/hsr-node
      - run: npm ci
        working-directory: packages/hsr-node-rpc
      - run: npm ci
        working-directory: packages/hsr-node-static
      - run: npm ci
        working-directory: tests/hsr-tests
      - run: npm run build

  test:
    name: test hsr
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm ci
        working-directory: packages/hsr-browser
      - run: npm ci
        working-directory: packages/hsr-browser-rpc
      - run: npm ci
        working-directory: packages/hsr-node
      - run: npm ci
        working-directory: packages/hsr-node-rpc
      - run: npm ci
        working-directory: packages/hsr-node-static
      - run: npm ci
        working-directory: tests/hsr-tests
      - run: npm run build
      - run: npm test
        working-directory: tests/hsr-tests

