name: build & test
on:
  push:
    branches:

jobs:
  build:
    name: Build hsr
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: lerna bootstrap
      - run: lerna run build

  test:
    name: test hsr
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci
      - run: lerna bootstrap
      - run: lerna run build
      - run: npm test
        working-directory: tests/hsr-tests

